import ThemeSwitcherButton, {
  themesArray,
} from "@/components/buttons/theme/ThemeSwitcherButton";
import { ThemeProvider } from "@/components/providers/theme/ThemeProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system" // <- system preference
          enableSystem={true}
          disableTransitionOnChange
          themes={themesArray}
        >
          {children}
          <ThemeSwitcherButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
